//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureME.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_FILES_STR_SETTINGS {
            get {
                return ((string)(this["PATH_FILES_STR_SETTINGS"]));
            }
            set {
                this["PATH_FILES_STR_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_LOCKED_SETTINGS {
            get {
                return ((bool)(this["IS_LOCKED_SETTINGS"]));
            }
            set {
                this["IS_LOCKED_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string USERNAME_FIELD_SETTINGS {
            get {
                return ((string)(this["USERNAME_FIELD_SETTINGS"]));
            }
            set {
                this["USERNAME_FIELD_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PASSWORD_FIELD_SETTINGS {
            get {
                return ((string)(this["PASSWORD_FIELD_SETTINGS"]));
            }
            set {
                this["PASSWORD_FIELD_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_HIDDEN_SETTINGS {
            get {
                return ((bool)(this["IS_HIDDEN_SETTINGS"]));
            }
            set {
                this["IS_HIDDEN_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOVED_IT {
            get {
                return ((bool)(this["LOVED_IT"]));
            }
            set {
                this["LOVED_IT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Liked it? Send us a react then!")]
        public string LOVED_IT_STR {
            get {
                return ((string)(this["LOVED_IT_STR"]));
            }
            set {
                this["LOVED_IT_STR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_MESSAGE_SENT {
            get {
                return ((bool)(this["IS_MESSAGE_SENT"]));
            }
            set {
                this["IS_MESSAGE_SENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_FOLDERS_STR_SETTINGS {
            get {
                return ((string)(this["PATH_FOLDERS_STR_SETTINGS"]));
            }
            set {
                this["PATH_FOLDERS_STR_SETTINGS"] = value;
            }
        }
    }
}
